In [158]:
import pandas as pd 
import numpy as np

In [159]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [160]:
batch_size=2
lRate = 0.05

Dataset

In [161]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [162]:
dataset=pd.DataFrame(data)

In [163]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [164]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [165]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [166]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [167]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [168]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [169]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [170]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [171]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [172]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [173]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [174]:
weight_1

array([[ 0.13936156, -0.54994978],
       [-0.91267969, -0.86689079],
       [-0.92175516,  0.80293424]])

In [175]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

#inner loop for iterating over all experiences


In [176]:
for n in range(100):    
    for m in range(len(X_norm)):
      output_1=X_norm[m]@weight_1 # output 1
      act_output=sigmoid(output_1).numpy() # activated output

      pred_output=act_output@weight_2 # predicted output
      pred_output=np.reshape(pred_output,(1,-1)); # reshaping the predicted output

      # computing the error at node K
      actualO = y_norm[0][0]; # actual output
      pOut = pred_output[0][0]; # predicted output
      errK = (actualO - pOut) * pOut * (1 - pOut); # error at node k

      # computing errors at the hidden layers
      hNodeErrs = np.empty(len(weight_2)); # populate the errors array with the number of nodes
      for i in range(len(weight_2)):
        outAtNode = act_output[i]; # activated output at node i
        hNodeErrs[i] = errK * weight_2[i][0] * (outAtNode * (1 - outAtNode)) # compute error at node i
      
      # using delta rule to update the first set of weights (weight_2)
      for i in range(len(weight_2)):
        weight_2[i][0] = weight_2[i][0] + lRate * errK * pOut

      # using delta rules to update weight_1
      for i in range(len(weight_1)):
        for j in range(len(weight_1[0])):
          weight_1[i][j] = weight_1[i][j] + lRate * hNodeErrs[j] * act_output[j]



In [177]:
weight_1

array([[ 0.11213205, -0.59367959],
       [-0.9399092 , -0.9106206 ],
       [-0.94898467,  0.75920442]])

In [178]:
weight_2


array([[0.63695739],
       [0.43999388]])